10. Codigo/ReciclaMaisBrasil/ReciclaMaisBrasil/Controllers/SolicitarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Models;
using Negocio.Business;
using ReciclaMaisBrasil.Util;
using System.IO;

namespace ReciclaMaisBrasil.Controllers
{
    public class SolicitarController : Controller
    {
        GerenciadorSolicitacao gerenciador = new GerenciadorSolicitacao();
        GerenciadorInstituicao gerenciadorI = new GerenciadorInstituicao();
        Pessoa user = (Pessoa)SessionHelper.Get(SessionKeys.USUARIO);
        // GET: Solicitar
        public ActionResult Index()
        {
            return View();
        }

        // GET: Solicitar/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Solicitar/Create
        public ActionResult Create()
        {
            TpReciclavel tp = new TpReciclavel();
            ViewBag.TipoReciclavel = new SelectList(tp.Reciclavel);
            ViewBag.Instituicao = new SelectList(gerenciadorI.ObterTodosInstituicao(), "IdUsuario","NmInstituicao");
            
            return View();
        }

        // POST: Solicitar/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "IdSolicitacao, CodSolicitacao, DtAbertura, DtEmAndamento,Status")]SolicitacaoColeta solicitacao, HttpPostedFile imagem)
        {
            try
            {
                byte[] arrayImagem = null;
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    imagem.InputStream.CopyTo(memoryStream);
                    arrayImagem = memoryStream.ToArray();
                }
                                    solicitacao.FotoReciclavel = arrayImagem;
                if (ModelState.IsValid)
                {

                    solicitacao.Status = 0;
                    solicitacao.IdPessoa = user.IdUsuario;
                    solicitacao.DtAbertura = DateTime.Now;

                    gerenciador.Adicionar(solicitacao);
                    return RedirectToAction("Index","HistoricoUsuario");
                }
               
            }
            catch
            {
                return View();
            }
            return View();
        }

        // GET: Solicitar/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Solicitar/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Solicitar/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Solicitar/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ValidarColeta()
        {
            return View();
        }
    }
}

10. Codigo/ReciclaMaisBrasil/ReciclaMaisBrasil/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Recicla Mais Brasil - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin:0px;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#" style="width:180px; height:80px; padding:7px 15px">
                    <img href="@Url.Action("Index","Home")" src=@Url.Content("~/Content/Images/logo-nav-top.svg") alt="Brand" style="width:150px;height:67.69px;">
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav fonte-texto-menu">
                    <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    <li>@Html.ActionLink("Cadastro", "Cadastro", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Como Funciona ?", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class=" body-content-fix">

        @RenderBody()
        
        <footer>
            <div class="row">
                <div class="jumbotron" id="terceiro" style="margin-bottom:0px !important;min-height: 768px !important;">
                    <div class="row row-centered  margem">
                        <img src="~/Content/Images/logo-bottom.svg" id="logo-bottom" />
                    </div>
                    <div class="row row-centered  margem">
                        <div class="col-md-2 col-centered "><img src="~/Content/Images/instagram-icon.png" id="logo-insta" /></div>
                        <div class="col-md-2 col-centered"><img src="~/Content/Images/twitter-icon.png" id="logo-twitter" /></div>
                        <div class="col-md-2 col-centered"><img src="~/Content/Images/facebook-icon.svg" id="logo-facebook" /></div>
                    </div>
                    <div class="row row-centered margem">
                        ©2017 - @DateTime.Now.Year - All rigths reserved to CAMNSystem
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

10. Codigo/ReciclaMaisBrasil/ReciclaMaisBrasil/Views/Shared/_LayoutInstituicao.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Recicla Mais Brasil - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin:0px;">
    <div class="navbar navbar-inverse navbar-fixed-top" style="position:static;">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="" style="width:180px; height:80px; padding:7px 15px">
                    <img href="@Url.Action("Index","Home")" src=@Url.Content("~/Content/Images/logo-nav-top.svg")  alt="Brand" style="width:150px;height:67.69px;">
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav fonte-texto-menu">
                    <li>@Html.ActionLink("Histórico", "Index", "Home")</li>
                    <li>@Html.ActionLink("Validar Coleta", "About", "Home")</li>
                    <li>@Html.ActionLink("Solicitações", "Contact", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Perfil <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Alterar Perfil", "Edit", "Instituicao")</li>
                            <li>@Html.ActionLink("Alterar Senha", "EditSenha", "Instituicao")</li>
                        </ul>
<li>@Html.ActionLink("Sair", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class=" body-content-fix">

        @RenderBody()
        
        <footer>
            <div class="row">
              <div class="row row-centered margem">
                ©2017 - @DateTime.Now.Year - All rigths reserved to CAMNSystem
              </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

10. Codigo/ReciclaMaisBrasil/ReciclaMaisBrasil/Views/Shared/_LayoutSemMenu.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Recicla Mais Brasil - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin:0px;">

    <div class=" body-content " id="body-fundo">

        @RenderBody()
        <footer>
            <div class="row row-centered margem">
                ©2017 - @DateTime.Now.Year - All rigths reserved to CAMNSystem
            </div>
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

10. Codigo/ReciclaMaisBrasil/ReciclaMaisBrasil/Views/Shared/_LayoutUsuario.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Recicla Mais Brasil - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @using ReciclaMaisBrasil.Util;  
    @using Model.Models;
</head>
@{ 
    Pessoa pessoa = (Pessoa) SessionHelper.Get(SessionKeys.USUARIO);
    

}
<body id="body-fundo" style="margin:0px;">
    <div class="navbar navbar-inverse navbar-fixed-top" style="position:static;margin-bottom:5px;">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index","HistoricoUsuario")" style="width:180px; height:80px; padding:7px 15px">
                    <img src=@Url.Content("~/Content/Images/logo-nav-top.svg")  alt="Brand" style="width:150px;height:67.69px;">
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav fonte-texto-menu" style="margin-bottom:5px;">
                    <li>@Html.ActionLink("Historico", "Index", "HistoricoUsuario")</li>
                    <li>@Html.ActionLink("Loja", "Index", "Loja")</li>
                    <li>@Html.ActionLink("Formas de Reciclagem", "Index", "FormasReciclagem")</li>
                    <li>@Html.ActionLink("Solicitar Coleta", "Create", "Solicitar")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Perfil <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Alterar Perfil", "Edit", "Pessoa")</li>
                            <li>@Html.ActionLink("Alterar Senha", "EditSenha", "Pessoa")</li>
                        </ul>
                    <li>@Html.ActionLink("Sair", "Logout", "HistoricoUsuario")</li>
                    <li><a href="@Url.Action("Index","Home")"><img src=@Url.Content("~/Content/Images/bell-icon.svg") id="bell-icon" /></a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class=" body-content" >
        @RenderBody()
    </div>
    


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/map.js")
    @RenderSection("scripts", required: false)
</body>
</html>