10. Codigo/ReciclaMaisBrasil/ReciclaMaisBrasil/Controllers/AdmProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Models;
using Negocio.Business;
using ReciclaMaisBrasil.Util;

namespace ReciclaMaisBrasil.Controllers
{
    public class AdmProdutoController : Controller
    {
        public GerenciadorProduto gerenciadoraP;
        public Pessoa user = (Pessoa) SessionHelper.Get(SessionKeys.USUARIO);

        public AdmProdutoController()
        {
            gerenciadoraP = new GerenciadorProduto();
        }
        // GET: AdmProduto
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdmProduto/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdmProduto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdmProduto/Create
        [HttpPost]
        public ActionResult Create(Produto prod)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    prod.IdAdmProduto = user.IdUsuario;
                    gerenciadoraP.Adicionar(prod);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdmProduto/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdmProduto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Produto prod)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    gerenciadoraP.Editar(prod);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdmProduto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdmProduto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult List()
        {
            return View(gerenciadoraP.ObterTodosAdm(user.IdUsuario));
        }
    }
}

10. Codigo/ReciclaMaisBrasil/ReciclaMaisBrasil/Views/AdmProduto/Create.cshtml
@model Model.Models.Produto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutSemMenu.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Produto</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.NmProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NmProduto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NmProduto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.DescProduto,  htmlAttributes : new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DescProduto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FotoProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FotoProduto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FotoProduto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row row-centered">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

10. Codigo/ReciclaMaisBrasil/ReciclaMaisBrasil/Views/AdmProduto/Edit.cshtml
@model Model.Models.Produto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutSemMenu.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdProduto)
        @Html.HiddenFor(model => model.IdAdmProduto)

        <div class="form-group">
            @Html.LabelFor(model => model.NmProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NmProduto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NmProduto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescProduto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescProduto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FotoProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FotoProduto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FotoProduto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

10. Codigo/ReciclaMaisBrasil/ReciclaMaisBrasil/Views/AdmProduto/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSemMenu.cshtml";
}
<div class="row row-centered " >
    <div class="col-centered">
        <a href="@Url.Action("Index","AdmProduto")">
            <img href="@Url.Action("Index","AdmProduto")" src=@Url.Content("~/Content/Images/logo-nav-top.svg") style="height:200px;width: 200px;" />
        </a>
    </div>


    
</div>
<div class="row row-centered">
    <div class="col-md-3 col-centered" id="btn-cadastrar-produto">
        <a href="@Url.Action("Create","AdmProduto")">
            <img href="@Url.Action("Create","Produto")" src=@Url.Content("~/Content/Images/btn-cadastrar-produto.svg") style="height: 200px;width: 200px;" />
       </a>
</div>
    <div class="col-md-3 col-centered" id="btn-cadastrar-produto">
        <a href="@Url.Action("Entregar","AdmProduto")">
            <img href="@Url.Action("Entregar","Produto")" src=@Url.Content("~/Content/Images/btn-entrega-produto.svg") style="height: 200px;width: 200px;" />
        </a>
</div>
    <div class="col-md-3 col-centered" id="btn-cadastrar-produto">
        <a href="@Url.Action("Edit","Pessoa")">
            <img href="@Url.Action("Edit","Pessoa")" src=@Url.Content("~/Content/Images/btn-alterar-cadastro.svg") style="height: 200px;width: 200px;" />
            </a>
</div>
</div>

    <div class="row row-centered ">
        <ul class="nav navbar-nav fonte-texto-menu col-centered">
            <li>@Html.ActionLink("Sair", "Logout", "Usuario")</li>
        </ul>
    </div>